services: 

  kafka: 
    image: 'bitnami/kafka:latest' 
    container_name: kafka 
    ports: 
      - '9092:9092' 
    environment: 
      - KAFKA_CFG_NODE_ID=0 
      - KAFKA_CFG_PROCESS_ROLES=controller,broker 
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT 
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 
    volumes: 
      - kafka_data:/bitnami/kafka 
    networks: 
      - cdc-network 

  mysql: 
    image: mysql:8.0 
    platform: linux/amd64 
    container_name: mysql-container 
    ports: 
      - "3307:3306" 
    environment: 
      - MYSQL_ROOT_PASSWORD=root 
    volumes: 
      - ./db_movies_netflix_transact.sql:/docker-entrypoint-initdb.d/init.sql 
      - mysql_data:/var/lib/mysql 
    command: 
      - '--server-id=223344' 
      - '--log-bin=mysql-bin' 
      - '--binlog_format=ROW' 
      - '--gtid-mode=ON' 
      - '--enforce-gtid-consistency=ON' 
    networks: 
      - cdc-network 

  debezium: 
    image: debezium/connect:2.5 
    platform: linux/amd64 
    container_name: debezium 
    depends_on: 
      - kafka 
      - mysql 
    ports: 
      - "8083:8083" 
    environment: 
      BOOTSTRAP_SERVERS: 'kafka:9092' 
      GROUP_ID: 1 
      CONFIG_STORAGE_TOPIC: my_connect_configs 
      OFFSET_STORAGE_TOPIC: my_connect_offsets 
      STATUS_STORAGE_TOPIC: my_connect_statuses 
    networks: 
      - cdc-network 

networks: 
  cdc-network: 
    driver: bridge 

volumes: 
  kafka_data: 
    driver: local 
  mysql_data: 
    driver: local 